version: "3.8"

services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/application
    depends_on:
      - mysql
      - php
  php:
    build:
      context: docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/application
  mysql:
    image: mysql:latest
    ports:
      - "3316:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./database/data/mysql:/var/lib/mysql

  composer:
    build:
      context: docker/composer
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/application

  artisan:
    build:
      context: docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/application
    entrypoint: ["php", "/var/www/application/artisan"]

